### ISSUE TITLE
Remove Axios as a dependency

### ISSUE THREAD

**Issue by gijsroge** [storyblok/storyblok-js-client#148] opened 2022-01-16 15:06 UTC
In line with this release https://github.com/storyblok/storyblok-js-client/releases/tag/v4.2.0

I think we can try and remove Axios as a dependency, I quickly looked at the source code to see if Axios was heavily integrated but it seems it's usage is very limited (but not sure). If so I think you should try and move away from Axios in favor of native Fetch.

Project's that try to minimize the need for third party dependencies are forced to use Axios when using Storyblok which is a shame.

Axios = 16kb
Storyblok js client = 9.6kb

So Axios is almost 2x the size of the Storyblok client.

**Comment by christianzoppi** [comment] 2022-01-17 05:47
Duplicate of #88

**Closed** 2022-01-17 10:25 UTC
