### ISSUE TITLE
bug: `fetchOptions` in `.getStory()` and `.getStories()` are Not Passed to `.get()` Internally

### ISSUE THREAD

**Issue by babs20** [storyblok/storyblok-js-client#755] opened 2024-01-19 15:10 UTC
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When passing `fetchOptions` to the  `.getStory()` or `.getStories()` methods the `fetchOptions` are not being persisted when those methods call `.get()`. This happens because `.getStory()` and `.getStories()` calls `this.client.setFetchOptions(fetchOptions)`.  `.get()` also calls `this.client.setFetchOptions(fetchOptions)`, but `fetchOptions` will be `undefined` at that point because `fetchOptions` is not passed from the other two methods internally.

---

## Expected Behavior

`fetchOptions` should work when using `.getStory()` or `.getStories()`

## Current Behavior

`fetchOptions` are not passed to the final `fetch` invocation when using `.getStory()` or `.getStories()`

## Steps to Reproduce

1. Instantiate a new JS client.
2. Create `fetchOptions`:
```ts
{
  headers: {
    'x-test': 'test',
  }
}
```
3. Create some demo params.
4. Call `sbClient.getStory('home', params, fetchOptions)` and ``sbClient.get(`cdn/stories/${slug}`, params, fetchOptions)``.
5. The `fetchOptions` in the first `getStory` call will not be added to the fetch.
6. To test call the `sbClient`  methods from client side code in the browser and inspect the request in the network tab.

If you need a code reproduction I can provide one.

**Comment by babs20** [comment] 2024-01-19 15:11
I would also be willing to create a PR to fix this issue. 🙂

**Comment by ryami333** [comment] 2024-06-19 18:24
@thiagosaife the PR has been open for a while now. Could you please give us an update? This one should be a slam dunk.

**Comment by ryami333** [comment] 2024-06-21 10:28
Potential duplicate of https://github.com/storyblok/storyblok-js-client/issues/827

**Comment by babs20** [comment] 2024-06-26 17:10
> Potential duplicate of #827

Yeah it looks like there is some overlap. Their solution goes a bit further in making these fetch options a per request rather than per client. Overall, I like their per request behavior better, but that seems like a larger package model change that Storyblok would need to discuss if they want to implement it.

Especially since this bug has now been present for 4 months, if there is more discussion for that type of change it would be nice to at least get #792 added in a minor or patch version before that PR, which I assume would need to be in a major since it changes the behavior of the client. 

If they end up going with #827, I would still like to get some of these tests implemented into their test suite, so that this type of thing doesn't happen in the future.

**Closed** 2024-08-20 12:52 UTC
