### ISSUE TITLE
fechOptions gets overwritten when doing multiple requests

### ISSUE THREAD

**Issue by max-g** [storyblok/storyblok-js-client#827] opened 2024-06-17 16:28 UTC
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When doing multiples Storyblok API calls using fetchOptions, they get overwritten with the values of the last call. I believe it's due to the fact that the fetchOptions are set in the client which is then shared for all requests. A direct use case is using the fetchOptions in a Next.js site where we use fetch options to configure caching behavior, eg: `{ next: { revalidate: 600, tags: ['homepage'] } }`. If we are to do multiple requests, the last value of the `{ next: {...} }` will be used for all requests; resulting in all request having the same revalidate and tags.

---

## Expected Behavior

Each requests should have it's own values for fetchOptions.

## Current Behavior

If we launch multiple requests, the last value provided for fetchOptions is used for all requests.

## Steps to Reproduce

1. Configure and use `StoryblokClient`
2. Make multiple calls to `.get()` for differents stories using different fetchOptions.
3. Using the custom fetch method we can log all args used, and see that it's always logging the last value of fetchOptions.

Here is an code sample for a Next.js route handler fetching multiple content from Storyblok to build a standard page.
We would like each `.get` call to provide it's own tags so that we can revalidate the cache whenever one of these pages get saved/published 

```
export async function GET() {
  const api = new StoryblokClient({
    accessToken: process.env.NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN,
    region: process.env.NEXT_PUBLIC_STORYBLOK_REGION,
    cache: {
      clear: 'auto',
      type: 'memory',
    },
    fetch(url, args) {
      console.log(url, args.next);
      return Promise.resolve(new Response(JSON.stringify({ message: 'fetch' })));
    },
  });

  await Promise.all([
    api.get('cdn/stories', {
      version: 'draft',
    }, { next: { tags: ['home'], revalidate: 3600 } }),

    api.get('cdn/stories/header', {
      version: 'draft',
    }, { next: { tags: ['header'], revalidate: 3600 } }),

    api.get('cdn/stories/footer', {
      version: 'draft',
    }, { next: { tags: ['footer'], revalidate: 3600 } }),

    api.get('cdn/stories/shared-meta', {
      version: 'draft',
    }, { next: { tags: ['meta'], revalidate: 3600 } }),

    api.get('cdn/stories/social-links', {
      version: 'draft',
    }, { next: { tags: ['links'], revalidate: 600 } }),
  ]);

  return Response.json({ message: 'fetched' });
}
``` 

```
## Output of the console.log

 GET /api/test 200 in 1141ms
https://api-us.storyblok.com/v2/cdn/stories?version=draft&token=<REDACTED_TOKEN>&cv=undefined { tags: [ 'links' ], revalidate: 600 }
https://api-us.storyblok.com/v2/cdn/stories/header?version=draft&token=<REDACTED_TOKEN>&cv=undefined { tags: [ 'links' ], revalidate: 600 }
https://api-us.storyblok.com/v2/cdn/stories/footer?version=draft&token=<REDACTED_TOKEN>&cv=undefined { tags: [ 'links' ], revalidate: 600 }
https://api-us.storyblok.com/v2/cdn/stories/shared-meta?version=draft&token=<REDACTED_TOKEN>&cv=undefined { tags: [ 'links' ], revalidate: 600 }
https://api-us.storyblok.com/v2/cdn/stories/social-links?version=draft&token=REDACTED_TOKEN&cv=undefined { tags: [ 'links' ], revalidate: 600 }
```

**Comment by ryami333** [comment] 2024-06-21 10:29
Potential duplicate of https://github.com/storyblok/storyblok-js-client/issues/755

**Comment by alexjoverm** [comment] 2024-08-14 11:23
Hey all, we're working on this soon. Just FYI, I shared more details here https://github.com/storyblok/storyblok-js-client/pull/828#issuecomment-2288487387

**Closed** 2024-08-20 12:52 UTC
