### ISSUE TITLE
Attempted import error: './index.js' does not contain a default export (imported as 'cjs')

### ISSUE THREAD

**Issue by rakshithasoma30** [storyblok/storyblok-js-client#184] opened 2022-03-23 07:43 UTC
./node_modules/storyblok-js-client/dist/index.mjs
Attempted import error: './index.js' does not contain a default export (imported as 'cjs').

getting this error while building after recent update of storyblok js client
@samuells

**Comment by Samuelsonvs** [comment] 2022-03-23 12:46
I have the same problem

**Comment by thiagosaife** [comment] 2022-03-23 13:56
@rakshithasoma30 I'm looking into it. Thanks for pointing this out.

**Comment by alexjoverm** [comment] 2022-03-23 19:20
@rakshithasoma30 @Samuelsonvs `storyblok-js-client` is used currently in multiple environments (webpack, vite, node, native ESM...) and in our SDKs demos is working correctly.

To understand and catch the issue, it'd be very helpful if you can provide a reproduction demo/repo for us to check it. Are you able to do that?

**Comment by rakshithasoma30** [comment] 2022-03-23 19:28
@alexjoverm we are using for nextjs 

Reproduction steps:

1. delete the existing node modules.
2. npm install
3. npm run build

Build is getting failed with the above error.

**Comment by thiagosaife** [comment] 2022-03-23 20:52
Hello @rakshithasoma30 
The problem was with the rollup build process. It was changed to enhance compatibility with Node 17, but I faced some other issues doing that. Anyway, I reverted these building changes and released version 4.3.1. Please, have a look with whit new version to see if everything got back in tracks.

**Comment by Samuelsonvs** [comment] 2022-03-23 21:42
> Hello @rakshithasoma30 The problem was with the rollup build process. It was changed to enhance compatibility with Node 17, but we raised some other issues doing that. Anyway, I reverted these building changes and released version [4.3.1](https://github.com/storyblok/storyblok-js-client/releases/tag/v4.3.1). Please, have a look on this new version to see if everything got back into tracks. And thanks for you help on Discord!

thanks problem solved

**Comment by rakshithasoma30** [comment] 2022-03-24 06:05
Thank you @thiagosaife  its working as expected now.

**Comment by thiagosaife** [comment] 2022-03-24 12:03
Glad to hear that. I will close this issue now. Thanks guys!

**Closed by thiagosaife** 2022-03-24 12:03 UTC
