### ISSUE TITLE
Feature request. Ability to create folder hierarchies in a single request

### ISSUE THREAD

**Issue by pshata** [storyblok/storyblok-js-client#519] opened 2023-04-03 17:04 UTC
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Description:
As a user, I often need to create folder hierarchies in my project, but the current process of creating each folder one by one is time-consuming. Therefore, I would like to request the ability to create folder hierarchies in a single request.

## Expected Behavior
To have the ability to create a shallow folder hierarchy in a single request.

```
const folderB = await client.post(`spaces/${STORYBLOK_SPACE_ID}/stories/`, {
            story: {
                slug: folderBSlug,
                name: folderBName,
                parent: {
                    slug: folderASlug,
                    name: folderAName,
                },
                is_folder: true,
            },
        });
```

## Current Behavior
To create a folder inside another folder, I need to send the first request to create the parent folder, and then send the second request to create the child folder.
```
const folderA = await client.post(`spaces/${STORYBLOK_SPACE_ID}/stories/`, {
            story: {
                slug: folderASlug,
                name: folderAName,
                parent_id: `${parentFolderId}`,
                is_folder: true,
            },
        });
const folderB = await client.post(`spaces/${STORYBLOK_SPACE_ID}/stories/`, {
            story: {
                slug: folderBSlug,
                name: folderBName,
                parent_id: folderA.story.id,
                is_folder: true,
            },
        });
```

**Comment by VojislavVlasic** [comment] 2023-04-05 09:50
Hello,
Since this is not a bug, but a Feature Request I'll close this issue.

**Closed by VojislavVlasic** 2023-04-05 09:50 UTC

**Comment by pshata** [comment] 2023-04-05 09:53
@VojislavVlasic What is an appropriate place for a feature request?

**Comment by VojislavVlasic** [comment] 2023-04-05 09:55
@pshata it would be Discord community if you're a Community user, other plans have Account Managers with whom they communicate.
